### ISSUE TITLE
Temperatures always say "sensor_unit_c", even if in F

### ISSUE THREAD

**Issue by ahknight** [hassio-addons/addon-prometheus#4]
# Problem/Motivation

> In America, we use Freedom units. /s

## Expected behavior

> The software should respect my Gawd-given right to use the wrong unit.

## Actual behavior

> It logged the correct numerical value (say, 90) but logged it under sensor_unit_c instead of sensor_unit_f where I'd expect it.

## Steps to reproduce

> Use Freedom units!

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mjrider** [comment]
This would be an issue with the prometheus integration, the exporter, in home-assistant and not the addon, 

Of course the correct solution would be using SI units
