### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kerryland** [hassio-addons/addon-prometheus#41]
I've just been through the same pain as described in issue #5.  *Please* change `README.md` and/or `DOCS.md` to clearly state that this addon isn't ready yet. This is very, very misleading:

> The installation of this add-on is pretty straightforward and not different in comparison to installing any other Home Assistant add-on.
>
>    Search for the "Prometheus" add-on in the Supervisor add-on store.
 >   Install the "Prometheus" add-on

I've spent an age trying to figure out what was wrong with my installation (there were some bogus error messages in my logs that led me astray).

Yes, you can do nothing again (like in #5), but that doesn't help the next person. Thanks.

EDIT: Actually, what's the status of this? I've now found the "beta" and "edge" repositories, which *do* have nice descriptions in them. Was this once-healthy and now broken? You don't use branches for development? 

Would it be useful if I tried out one of these? Which one?

**Comment by frenck** [comment]
<img width="813" alt="CleanShot 2022-03-20 at 22 27 55@2x" src="https://user-images.githubusercontent.com/195327/159186685-2b67451e-6bbb-4ba3-bce9-dc444f6bf81e.png">

We clearly show there are no releases and the project stage is development. Directly under the title.

> EDIT: Actually, what's the status of this? 

Development.

>  I've now found the "beta" and "edge" repositories, which do have nice descriptions in them. Was this once-healthy and now broken? You don't use branches for development?

Those are development add-on repositories and not meant for production.

**Comment by kerryland** [comment]
> Those are development add-on repositories and not meant for production.

...so why are you also using *this* repository for code that is not ready for production? 

> We clearly show there are no releases and the project stage is development. 

If it was clear it wouldn't repeatedly be a problem. The real-world evidence is against you, but hey, I understand that fixing it would require a huge amount of effort on your part and other people's time has no value.

**Comment by frenck** [comment]
> this repository

I don't get this comment. This is GitHub, this is where software is developed. Your comment there makes absolutelty 0 sense.

> If it was clear it wouldn't repeatedly be a problem. 

Above all, it don't care.

../Frenck

**Comment by Davincible** [comment]
Have to say it's pretty confusing since the doc says its supposed to be there, but it's not 

https://github.com/hassio-addons/addon-prometheus/blob/844a3a4985a3b968d45d6608afeea54509407342/prometheus/DOCS.md?plain=1#L7-L10
