### ISSUE TITLE
Not listed in Add-on Store

### ISSUE THREAD

**Issue by robearlam** [hassio-addons/addon-prometheus#5]
# Problem/Motivation

Unable to find add-on listen in Add-on Store

## Expected behavior

Expect add-on to be listed in Add-on Store

## Actual behavior

Add-on not listed in Add-on Store

## Steps to reproduce

Search for the "Prometheus" add-on in the Supervisor add-on store, as per installation guide.

**Comment by thavini** [comment]
You have to add the beta store git repo to be able to find the at this moment beta version of this plugin.

**Comment by robearlam** [comment]
Awesome, that did the job cheers.

It would probably be useful to update the installation docs to include that step?

**Comment by thavini** [comment]
It would indeed be, but the docs probably already handling it like it is a major version. Not sure about it but it might just be from a template.

**Comment by frenck** [comment]
This add-on isn't released yet, hence it isn't in the add-on store.
