### ISSUE TITLE
Installation problem...

### ISSUE THREAD

**Issue by mcarbonneaux** [hassio-addons/addon-prometheus#55]
i whant to install "addon-prometheus" from homeassistant supervisor/repository...

after sseeing some issue, i've found that addon are only in the beta repository... https://github.com/hassio-addons/repository-beta...

i've tryed to add https://github.com/hassio-addons/repository-beta...
but after adding the beta repo, i dont see prometheus addon....

i've searched a litle more for why... 

i've seen some thing (but i've not found why) ...
1 - the addon-prometheus are the only addon that are only in the beta repo...
2 - the version referenced in the beta repository are "1.0.0-beta.0", that are very old (corespond to the last tags on the repository).
3 - the same with the docker image on docker hub....
4 - no more gitlab ci on the https://gitlab.com/hassio-addons vs other addon (but you have github flow).

there other way to install and test this plugin ? i'm on haos....

**Comment by mcarbonneaux** [comment]
after seeing the build of the github flow i've seen you deploy in edge (and no more in beta)...

i've try to add edge repository... and prometheus not appear in the liste of addon...

i've missed somphing ?

**Comment by frenck** [comment]
> there other way to install and test this plugin ?

By using this repository. This add-on hasn't been released.
You can use it as is (as source), but it isn't for production use.

../Frenck

**Comment by mcarbonneaux** [comment]
the adding of the edge repository needed a reboot to see the prometheus add-on.

> You can use it as is (as source), but it isn't for production use.

there another way to do it and abel to modify to correct the plugin ?

**Comment by frenck** [comment]
This is a source code repository. This add-on is not published.

End of story.

**Comment by frenck** [comment]
> if you don't want contribution don't publish it...

You are mixing up two things. Being open source and open to contributions doesn't mean every contribution is accepted. Yours wasn't. Sorry.

> not publish it publicly on github !

I think I decide that myself, thanks. Feel free to make different decisions in your own projects.

> and why cannot test it ? i whant to learn !?

Go ahead, the source is here, do what you want with it. As per license.

> there any problem on that ?

Not at all.

> but on haos how to do this ? with web terminal ?

Sure, depends on what you prefer for your development environment. Nevertheless, that is more a question of how Home Assistant add-ons work (and not related to this add-on).

Feel free to read up and learn about add-on development in the developer documentation Home Assistant provides:

<https://developers.home-assistant.io/docs/add-ons>

../Frenck

**Comment by mcarbonneaux** [comment]
> You are mixing up two things. Being open source and open to contributions doesn't mean every contribution is accepted. Yours wasn't. Sorry.

i don't speek about open contribution... you are free to accept it... but the way you answer is not good... and too radical...

I'm just asking for explanations/documentation on how to test your add on.
i'understand this add on a not production ready... this not efraid me...
and my pr is only to modify documentation to aide other people to test and contribut...

because i think many other can contribut i think is necessary to document... event if is in dev mode...

i know how prometheus work (i use it in production), docker too, but i need to anderstand how to test you add on with haos...
and how to modify it, to be abel to contribut... i don't know the build ecosystem of ha add-on...

**Comment by frenck** [comment]
> i don't speek about open contribution... you are free to accept it... 

Short and to the point. I don't spoonfeed (if that is what you have been looking for). Sorry.

> I'm just asking for explanations/documentation on how to test your add on.

Just like any other add-on, see linked documentation above.

> and my pr is only to modify documentation to aide other people to test and contribute...

I understood not what it was for, hence declined. Sorry.

> i don't know the build ecosystem of ha add-on...

Can't help you with that. Feel free to read up and learn using the resources available in many places.

../Frenck
