### ISSUE TITLE
Fix typo in shared directory creation

### ISSUE THREAD

**Issue by fliphess** [hassio-addons/addon-prometheus#6]
# Problem/Motivation

I've found a typo in the directory path in the init scripts and it itched my OCD a bit so I decided to push a fix :) 
As requested first only an issue instead of a PR. 

## Expected behavior

The directory should only be created once. (Even though this isn't much of a real issue as it's created with `mkdir -p`)

## Actual behavior

The mkdir is run on every startup. 

Motivation: My shared directory is on an NFS share, this mkdir takes a few more seconds during startup.

## Proposed changes

See commit: https://github.com/fliphess/addon-prometheus/commit/9d633846059d4e626aad01d2a25fbbdc80827c1a

Pushing a PR is easy done, so please let me know if this is appreciated. :)

**Comment by frenck** [comment]
The construct of running system data folders on a network mount, isn't supported by the Home Assistant project and not a consideration.

**Comment by fliphess** [comment]
I know and this bug report is not about the NFS mount :) 
 (I moved away from that yesterday: The performance impact is too high) 

This bug is about the typo in the scripts as shown in the commit in my fork. Do you want a PR for that or is this bug a requirement for something?

**Comment by mjrider** [comment]
yes the PR is welcom
